ci: add cache-to to buildx (#135)
* ci: add cache-to to buildx

* refactor: build cache

* refactor: optimize image cache

* ci: set max-parallel to 2 in workflow configurations

* fix: go dev deps missing

* ci: change ci condition

* refactor(hbase): update dockerfile

* refactor(spark): update dockerfile

* refactor(nifi): disable 1.27.0

* refactor: enable all product to built

* ci: translate zh to en

---------

Co-authored-by: wanghuagang <huagang.wang@tendata.cn>

diff --git a/hadoop/Dockerfile b/hadoop/Dockerfile
--- a/hadoop/Dockerfile
+++ b/hadoop/Dockerfile
@@ -1,70 +1,34 @@
 # syntax=docker/dockerfile:1
 # check=error=true
 
-## stage: async-profiler-builder
-FROM zncdatadev/image/java-devel AS async-profiler-builder
 
+## stage: hadoop-builder
+FROM zncdatadev/image/java-devel AS hadoop-builder
+
+ARG PRODUCT_VERSION
+ARG PROTOBUF_VERSION
 ARG ASYNC_PROFILER_VERSION
+ARG JMX_EXPORTER_VERSION
+ARG OAUTH2_PROXY_VERSION
 
 WORKDIR /build
 
 # setup async-profiler
 RUN <<EOF
+    set -ex
     ARCH=$(uname -m)
-    microdnf update
-
-    # build musl-gcc
-    # ref: https://github.com/async-profiler/async-profiler/blob/master/Dockerfile
-    microdnf install kernel-headers
-    mkdir /build/musl-gcc
-    pushd /build/musl-gcc
-    # https://musl.libc.org/releases/musl-1.2.5.tar.gz
-    curl -sSfL \
-        https://musl.libc.org/releases/musl-1.2.5.tar.gz \
-        | tar xzf - --strip-components=1
-    ./configure --disable-shared --prefix=/usr/local/musl
-    make -j$(nproc) && make install && make clean
-    ln -s /usr/include/{asm,asm-generic,linux} /usr/local/musl/include/
-    popd
-
-    # build patchelf
-    # ref: https://github.com/NixOS/patchelf?tab=readme-ov-file#compiling-and-testing
-    microdnf install autoconf automake
-    mkdir /build/patchelf
-    pushd /build/patchelf
-    # https://github.com/NixOS/patchelf/archive/refs/tags/0.18.0.tar.gz
-    curl -sSfL \
-        https://github.com/NixOS/patchelf/archive/refs/tags/0.18.0.tar.gz \
-        | tar xzf - --strip-components=1
-    ./bootstrap.sh
-    ./configure
-    make -j$(nproc) && make check && make install
-    popd
+    ARCH="${ARCH/x86_64/x64}"
+    ARCH="${ARCH/amd64/x64}"
+    ARCH="${ARCH/aarch64/arm64}"
 
     # build async-profiler
-    # ref: https://github.com/async-profiler/async-profiler/blob/master/.github/workflows/test-and-publish-nightly.yml
-    mkdir -p /build/async-profiler
-    pushd /build/async-profiler
-    # https://github.com/async-profiler/async-profiler/archive/refs/tags/v3.0.tar.gz
+    # https://github.com/async-profiler/async-profiler/releases/download/v3.0/async-profiler-3.0-linux-x64.tar.gz
     curl -sSfL \
-        httphttps://github.com/async-profiler/async-profiler/archive/refs/tags/v${ASYNC_PROFILER_VERSION}.tar.gz \
-        | tar xzf - --strip-components=1
-    make CC=/usr/local/musl/bin/musl-gcc release
-    # artifact loaction: ./async-profiler-3.0-linux-arm64.tar.gz
-    tar zx ./async-profiler-${ASYNC_PROFILER_VERSION}-linux-${ARCH}.tar.gz -C /kubedoop/
-    popd
+        https://github.com/async-profiler/async-profiler/releases/download/v${ASYNC_PROFILER_VERSION}/async-profiler-${ASYNC_PROFILER_VERSION}-linux-${ARCH}.tar.gz \
+        | tar -zxf - -C /kubedoop
+
+    ln -s /kubedoop/async-profiler-${ASYNC_PROFILER_VERSION}-linux-${ARCH} /kubedoop/async-profiler
 EOF
-
-
-## stage: builder
-FROM zncdatadev/image/java-devel AS java-builder
-
-ARG PRODUCT_VERSION
-ARG PROTOBUF_VERSION
-ARG JMX_EXPORTER_VERSION
-ARG OAUTH2_PROXY_VERSION
-
-WORKDIR /build
 
 COPY kubedoop/jmx/config-${JMX_EXPORTER_VERSION} /kubedoop/jmx
 
@@ -77,10 +41,28 @@ RUN <<EOF
     ln -s /kubedoop/jmx/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar /kubedoop/jmx/jmx_prometheus_javaagent.jar
 EOF
 
+# setup oauth2-proxy
+RUN <<EOF
+    ARCH=$(uname -m)
+    ARCH="${ARCH/x86_64/amd64}"
+    ARCH="${ARCH/aarch64/arm64}"
+
+    mkdir /kubedoop/oauth2-proxy
+    cd /kubedoop/oauth2-proxy
+
+    curl -sSfL \
+        https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-${ARCH}.tar.gz \
+        | tar xzf - --strip-components=1
+
+    # smoke test
+    /kubedoop/oauth2-proxy/oauth2-proxy --version
+EOF
+
 # Setup protobuf
 # ref: https://github.com/apache/hadoop/blob/trunk/dev-support/docker/pkg-resolver/install-protobuf.sh
 ENV PROTOBUF_HOME=/opt/protobuf
 RUN <<EOF
+    set -ex
     mkdir -p /build/protobuf-src
     pushd /build/protobuf-src
     PROTOBUF_LANGUAGE_VERSION=$PROTOBUF_VERSION
@@ -95,9 +77,14 @@ RUN <<EOF
     ./configure --prefix=${PROTOBUF_HOME}
     make -j$(nproc)
     make install
-    ln -s ${PROTOBUF_HOME}/bin/protoc /usr/bin/protoc
     popd
+
+    # cleanup source
+    rm -rf /build/protobuf-src
+
 EOF
+
+ENV PATH="${PATH}:${PROTOBUF_HOME}/bin"
 
 # smoke test
 RUN protoc --version
@@ -109,24 +96,42 @@ RUN <<EOF
     microdnf update
     microdnf install boost1.78-devel
     microdnf clean all
+    rm -rf /var/cache/yum
 EOF
 
 COPY kubedoop /build/
 
+# Setup hadoop
 RUN <<EOF
+    set -ex
     mkdir -p /build/hadoop-src
     pushd /build/hadoop-src
     curl -sSfL \
         https://github.com/apache/hadoop/archive/refs/tags/rel/release-${PRODUCT_VERSION}.tar.gz \
         | tar xzf - --strip-components=1
     /build/patches/apply_patches.sh /build/patches/${PRODUCT_VERSION}
-    mvn --no-transfer-progress clean package -Pdist,native -pl '!hadoop-tools/hadoop-pipes,!hadoop-yarn-project,!hadoop-mapreduce-project,!hadoop-minicluster' -Drequire.fuse=true -DskipTests -Dmaven.javadoc.skip=true
+    mvn \
+        --batch-mode \
+        --no-transfer-progress \
+        clean \
+        package \
+        -Pdist,native \
+        -pl '!hadoop-tools/hadoop-pipes,!hadoop-yarn-project,!hadoop-mapreduce-project,!hadoop-minicluster' \
+        -Drequire.fuse=true \
+        -DskipTests \
+        -Dmaven.javadoc.skip=true
 
     cp -r hadoop-dist/target/hadoop-${PRODUCT_VERSION} /kubedoop/hadoop-${PRODUCT_VERSION}
     cp hadoop-hdfs-project/hadoop-hdfs-native-client/target/main/native/fuse-dfs/fuse_dfs /kubedoop/hadoop-${PRODUCT_VERSION}/bin
 
     ln -s /kubedoop/hadoop-${PRODUCT_VERSION} /kubedoop/hadoop
     popd
+
+    # cleanup source
+    rm -rf /build/hadoop-src
+
+    # cleanup cache
+    rm -rf /root/.m2
 EOF
 
 # smoke test
@@ -143,24 +148,6 @@ RUN <<EOF
     /usr/local/bin/log4shell patch --backup --force-patch --json hadoop-${PRODUCT_VERSION}
 EOF
 
-RUN <<EOF
-set -ex
-ARCH=$(uname -m)
-ARCH="${ARCH/x86_64/amd64}"
-ARCH="${ARCH/aarch64/arm64}"
-
-mkdir /kubedoop/oauth2-proxy
-cd /kubedoop/oauth2-proxy
-
-curl -sSfL \
-    https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-${ARCH}.tar.gz \
-    | tar xzf - --strip-components=1
-
-EOF
-
-# smoke test
-RUN /kubedoop/oauth2-proxy/oauth2-proxy --version
-
 
 ## stage: final
 FROM zncdatadev/image/java-base
@@ -169,8 +156,7 @@ ARG PRODUCT_VERSION
 
 WORKDIR /kubedoop
 
-COPY --from=async-profiler-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
-COPY --from=java-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
+COPY --from=hadoop-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
 
 ENV HADOOP_HOME=/kubedoop/hadoop
 ENV HADOOP_CONF_DIR="${HADOOP_HOME}/etc/hadoop" \
diff --git a/hbase/Dockerfile b/hbase/Dockerfile
--- a/hbase/Dockerfile
+++ b/hbase/Dockerfile
@@ -1,14 +1,34 @@
 # syntax=docker/dockerfile:1
 # check=error=true
 
+
 ## stage: hbase-builder
-FROM zncdatadev/image/java-devel AS java-builder
+FROM zncdatadev/image/java-devel AS hbase-builder
 
 ARG PRODUCT_VERSION
 ARG HADOOP_VERSION
+ARG ASYNC_PROFILER_VERSION
 # 2.6 exports jmx and prometheus metrics by default
 ARG JMX_EXPORTER_VERSION=""
 ARG OAUTH2_PROXY_VERSION
+
+
+# setup async-profiler
+RUN <<EOF
+    set -ex
+    ARCH=$(uname -m)
+    ARCH="${ARCH/x86_64/x64}"
+    ARCH="${ARCH/amd64/x64}"
+    ARCH="${ARCH/aarch64/arm64}"
+
+    # build async-profiler
+    # https://github.com/async-profiler/async-profiler/releases/download/v3.0/async-profiler-3.0-linux-x64.tar.gz
+    curl -sSfL \
+        https://github.com/async-profiler/async-profiler/releases/download/v${ASYNC_PROFILER_VERSION}/async-profiler-${ASYNC_PROFILER_VERSION}-linux-${ARCH}.tar.gz \
+        | tar -zxf - -C /kubedoop
+
+    ln -s /kubedoop/async-profiler-${ASYNC_PROFILER_VERSION}-linux-${ARCH} /kubedoop/async-profiler
+EOF
 
 # setup jmx_exporter
 WORKDIR /kubedoop/jmx
@@ -30,11 +50,28 @@ RUN <<EOF
     fi
 EOF
 
+# setup oauth2-proxy
+RUN <<EOF
+    ARCH=$(uname -m)
+    ARCH="${ARCH/x86_64/amd64}"
+    ARCH="${ARCH/aarch64/arm64}"
+
+    mkdir /kubedoop/oauth2-proxy
+    cd /kubedoop/oauth2-proxy
+
+    curl -sSfL \
+        https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-${ARCH}.tar.gz \
+        | tar xzf - --strip-components=1
+
+    # smoke test
+    /kubedoop/oauth2-proxy/oauth2-proxy --version
+EOF
+
 WORKDIR /build
 COPY /kubedoop/ /build/
 
 RUN <<EOF
-    set -e
+    set -ex
     mkdir -p /build/hbase-src
     pushd /build/hbase-src
     curl -sSfL \
@@ -42,198 +79,156 @@ RUN <<EOF
         | tar xzf - --strip-components=1
     /build/patches/apply_patches.sh /build/patches/${PRODUCT_VERSION}
 
-    mvn --batch-mode --no-transfer-progress -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP_VERSION} clean install assembly:single -DskipTests -Dcheckstyle.skip=true -Prelease
+    mvn \
+        --batch-mode \
+        --no-transfer-progress \
+        -Dhadoop.profile=3.0 \
+        -Dhadoop-three.version=${HADOOP_VERSION} \
+        clean \
+        install \
+        assembly:single \
+        -DskipTests \
+        -Dcheckstyle.skip=true \
+        -Prelease
 
     tar -xzf hbase-assembly/target/hbase-${PRODUCT_VERSION}-bin.tar.gz -C /kubedoop
     ln -s /kubedoop/hbase-${PRODUCT_VERSION} /kubedoop/hbase
     popd
 
-EOF
+    # cleanup source
+    rm -rf /build/hbase-src
 
-# smoke test
-RUN /kubedoop/hbase-${PRODUCT_VERSION}/bin/hbase version
-
-RUN <<EOF
-set -ex
-ARCH=$(uname -m)
-ARCH="${ARCH/x86_64/amd64}"
-ARCH="${ARCH/aarch64/arm64}"
-
-mkdir /kubedoop/oauth2-proxy
-cd /kubedoop/oauth2-proxy
-
-curl -sSfL \
-    https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-${ARCH}.tar.gz \
-    | tar xzf - --strip-components=1
+    # cleanup cache
+    rm -rf /root/.m2
+    rm -rf /root/.npm
 
 EOF
 
 # smoke test
-RUN /kubedoop/oauth2-proxy/oauth2-proxy --version
+RUN /kubedoop/hbase/bin/hbase version
 
 
-## stage: async-profiler-builder
-FROM zncdatadev/image/java-devel AS async-profiler-builder
+# ## stage: hbase-operator-tools-builder
+# FROM zncdatadev/image/java-devel AS hbase-operator-tools-builder
 
-ARG ASYNC_PROFILER_VERSION
+# ARG PRODUCT_VERSION
+# ARG HBASE_OPERATOR_TOOLS_VERSION
+# ARG HBASE_THIRDPARTY_VERSION
 
-WORKDIR /build
+# WORKDIR /build
 
-# setup async-profiler
-RUN <<EOF
-    ARCH=$(uname -m)
-    microdnf update
+# # setup hbase-operator-tools
+# RUN <<EOF
+#     set -ex
+#     mkdir -p /build/hbase-operator-tools-src
+#     pushd /build/hbase-operator-tools-src
 
-    # build musl-gcc
-    # ref: https://github.com/async-profiler/async-profiler/blob/master/Dockerfile
-    microdnf install kernel-headers
-    mkdir /build/musl-gcc
-    pushd /build/musl-gcc
-    # https://musl.libc.org/releases/musl-1.2.5.tar.gz
-    curl -sSfL \
-        https://musl.libc.org/releases/musl-1.2.5.tar.gz \
-        | tar xzf - --strip-components=1
-    ./configure --disable-shared --prefix=/usr/local/musl
-    make -j$(nproc) && make install && make clean
-    ln -s /usr/include/{asm,asm-generic,linux} /usr/local/musl/include/
-    popd
+#     # if HBASE_OPERATOR_TOOLS_VERSION contains '-', it is a snapshot version, we need to
+#     # split it. the first part is version, the second part is the commit hash
+#     # use the commit hash to download the source code.
+#     if [[ ${HBASE_OPERATOR_TOOLS_VERSION} == *-* ]]; then
+#         version=$(echo ${HBASE_OPERATOR_TOOLS_VERSION} | cut -d '-' -f 1)
+#         sha=$(echo ${HBASE_OPERATOR_TOOLS_VERSION} | cut -d '-' -f 2)
+#         HBASE_OPERATOR_TOOLS_VERSION="${version}-SNAPSHOT"
+#         curl -sSfL \
+#             https://github.com/apache/hbase-operator-tools/archive/${sha}.tar.gz \
+#             | tar xzf - --strip-components=1
+#     else
+#         curl -sSfL \
+#             https://github.com/apache/hbase-operator-tools/archive/refs/tags/rel/${HBASE_OPERATOR_TOOLS_VERSION}.tar.gz \
+#             | tar xzf - --strip-components=1
+#     fi
 
-    # build patchelf
-    # ref: https://github.com/NixOS/patchelf?tab=readme-ov-file#compiling-and-testing
-    microdnf install autoconf automake
-    mkdir /build/patchelf
-    pushd /build/patchelf
-    # https://github.com/NixOS/patchelf/archive/refs/tags/0.18.0.tar.gz
-    curl -sSfL \
-        https://github.com/NixOS/patchelf/archive/refs/tags/0.18.0.tar.gz \
-        | tar xzf - --strip-components=1
-    ./bootstrap.sh
-    ./configure
-    make -j$(nproc) && make check && make install
-    popd
+#     # build hbase-operator-tools
+#     mvn \
+#         --no-transfer-progress \
+#         -Dhbase.version=${PRODUCT_VERSION} \
+#         -Dhbase-thirdparty.version=${HBASE_THIRDPARTY_VERSION} \
+#         -DskipTests \
+#         package assembly:single
 
-    # build async-profiler
-    # ref: https://github.com/async-profiler/async-profiler/blob/master/.github/workflows/test-and-publish-nightly.yml
-    mkdir -p /build/async-profiler
-    pushd /build/async-profiler
-    # https://github.com/async-profiler/async-profiler/archive/refs/tags/v3.0.tar.gz
-    curl -sSfL \
-        httphttps://github.com/async-profiler/async-profiler/archive/refs/tags/v${ASYNC_PROFILER_VERSION}.tar.gz \
-        | tar xzf - --strip-components=1
-    make CC=/usr/local/musl/bin/musl-gcc release
-    # artifact loaction: ./async-profiler-3.0-linux-arm64.tar.gz
-    tar zx ./async-profiler-${ASYNC_PROFILER_VERSION}-linux-${ARCH}.tar.gz -C /kubedoop/
-    popd
-EOF
+#     tar -xzf hbase-operator-tools-assembly/target/hbase-operator-tools-${HBASE_OPERATOR_TOOLS_VERSION}-bin.tar.gz -C /kubedoop
+#     ln -s /kubedoop/hbase-operator-tools-${HBASE_OPERATOR_TOOLS_VERSION} /kubedoop/hbase-operator-tools
+#     popd
+
+#     # cleanup source
+#     rm -rf /build/hbase-operator-tools-src
+
+#     # cleanup cache
+#     rm -rf /root/.m2
+# EOF
 
 
-## stage: hbase-operator-tools-builder
-FROM zncdatadev/image/java-devel AS hbase-operator-tools-builder
+# ## stage: phoenix-builder
+# FROM zncdatadev/image/java-devel AS phoenix-builder
 
-ARG PRODUCT_VERSION
-ARG HBASE_OPERATOR_TOOLS_VERSION
-ARG HBASE_THIRDPARTY_VERSION
+# ARG PRODUCT_VERSION
+# ARG HADOOP_VERSION
+# ARG PHOENIX_VERSION
+# ARG HBASE_PROFILE_VERSION
 
-WORKDIR /build
+# WORKDIR /build
+# # setup phoenix
+# RUN <<EOF
+#     set -ex
+#     mkdir -p /build/phoenix-src
+#     pushd /build/phoenix-src
 
-RUN <<EOF
-    set -ex
-    mkdir -p /build/hbase-operator-tools-src
-    pushd /build/hbase-operator-tools-src
+#     # Phonix repoisotry is https://github.com/apache/phoenix,
+#     # release download url is https://github.com/apache/phoenix/archive/refs/tags/5.2.1.tar.gz
+#     # If PHONIX_VERSION contains '-', it is a snapshot version, we need to
+#     # split it. the first part is version, the second part is the commit hash
+#     # use the commit hash to download the source code.
+#     if [[ ${PHOENIX_VERSION} == *-* ]]; then
+#         version=$(echo ${PHOENIX_VERSION} | cut -d '-' -f 1)
+#         sha=$(echo ${PHOENIX_VERSION} | cut -d '-' -f 2)
+#         PHOENIX_VERSION="${version}-SNAPSHOT"
+#         curl -sSfL \
+#             https://github.com/apache/phoenix/archive/${sha}.tar.gz \
+#             | tar xzf - --strip-components=1
+#     else
+#         curl -sSfL \
+#             https://github.com/apache/phoenix/archive/refs/tags/${PHOENIX_VERSION}.tar.gz \
+#             | tar xzf - --strip-components=1
+#     fi
 
-    # if HBASE_OPERATOR_TOOLS_VERSION contains '-', it is a snapshot version, we need to
-    # split it. the first part is version, the second part is the commit hash
-    # use the commit hash to download the source code.
-    if [[ ${HBASE_OPERATOR_TOOLS_VERSION} == *-* ]]; then
-        version=$(echo ${HBASE_OPERATOR_TOOLS_VERSION} | cut -d '-' -f 1)
-        sha=$(echo ${HBASE_OPERATOR_TOOLS_VERSION} | cut -d '-' -f 2)
-        HBASE_OPERATOR_TOOLS_VERSION="${version}-SNAPSHOT"
-        curl -sSfL \
-            https://github.com/apache/hbase-operator-tools/archive/${sha}.tar.gz \
-            | tar xzf - --strip-components=1
-    else
-        curl -sSfL \
-            https://github.com/apache/hbase-operator-tools/archive/refs/tags/rel/${HBASE_OPERATOR_TOOLS_VERSION}.tar.gz \
-            | tar xzf - --strip-components=1
-    fi
-    mvn \
-        --batch-mode \
-        --no-transfer-progress \
-        -Dhbase.version=${PRODUCT_VERSION} \
-        -Dhbase-thirdparty.version=${HBASE_THIRDPARTY_VERSION} \
-        -DskipTests \
-        package assembly:single
+#     # build phoenix
+#     mvn \
+#         --no-transfer-progress \
+#         -Dhbase.version=${PRODUCT_VERSION} \
+#         -Dhbase.profile=${HBASE_PROFILE_VERSION} \
+#         -Dhadoop.version=${HADOOP_VERSION} \
+#         -DskipTests \
+#         -Dcheckstyle.skip=true \
+#         clean \
+#         package
 
-    tar -xzf hbase-operator-tools-assembly/target/hbase-operator-tools-${HBASE_OPERATOR_TOOLS_VERSION}-bin.tar.gz -C /kubedoop
-    ln -s /kubedoop/hbase-operator-tools-${HBASE_OPERATOR_TOOLS_VERSION} /kubedoop/hbase-operator-tools
-    popd
-EOF
+#     mkdir /kubedoop/phoenix-${HBASE_PROFILE_VERSION}-${PHOENIX_VERSION}-bin
+#     tar -xzf phoenix-assembly/target/phoenix-hbase-*-bin.tar.gz -C /kubedoop/phoenix-${HBASE_PROFILE_VERSION}-${PHOENIX_VERSION}-bin --strip-components=1
+#     ln -s /kubedoop/phoenix-${HBASE_PROFILE_VERSION}-${PHOENIX_VERSION}-bin /kubedoop/phoenix
+#     popd
 
+#     # cleanup source
+#     rm -rf /build/phoenix-src
 
-## stage: phoenix-builder
-FROM zncdatadev/image/java-devel AS phoenix-builder
-
-ARG PRODUCT_VERSION
-ARG HADOOP_VERSION
-ARG PHOENIX_VERSION
-ARG HBASE_PROFILE_VERSION
-
-WORKDIR /build
-RUN <<EOF
-    set -ex
-    mkdir -p /build/phoenix-src
-    pushd /build/phoenix-src
-
-    # Phonix repoisotry is https://github.com/apache/phoenix,
-    # release download url is https://github.com/apache/phoenix/archive/refs/tags/5.2.1.tar.gz
-    # If PHONIX_VERSION contains '-', it is a snapshot version, we need to
-    # split it. the first part is version, the second part is the commit hash
-    # use the commit hash to download the source code.
-    if [[ ${PHOENIX_VERSION} == *-* ]]; then
-        version=$(echo ${PHOENIX_VERSION} | cut -d '-' -f 1)
-        sha=$(echo ${PHOENIX_VERSION} | cut -d '-' -f 2)
-        PHOENIX_VERSION="${version}-SNAPSHOT"
-        curl -sSfL \
-            https://github.com/apache/phoenix/archive/${sha}.tar.gz \
-            | tar xzf - --strip-components=1
-    else
-        curl -sSfL \
-            https://github.com/apache/phoenix/archive/refs/tags/${PHOENIX_VERSION}.tar.gz \
-            | tar xzf - --strip-components=1
-    fi
-
-    mvn \
-        --batch-mode \
-        --no-transfer-progress \
-        -Dhbase.version=${PRODUCT_VERSION} \
-        -Dhbase.profile=${HBASE_PROFILE_VERSION} \
-        -Dhadoop.version=${HADOOP_VERSION} \
-        -DskipTests \
-        -Dcheckstyle.skip=true \
-        clean \
-        package
-
-    mkdir /kubedoop/phoenix-${HBASE_PROFILE_VERSION}-${PHOENIX_VERSION}-bin
-    tar -xzf phoenix-assembly/target/phoenix-hbase-*-bin.tar.gz -C /kubedoop/phoenix-${HBASE_PROFILE_VERSION}-${PHOENIX_VERSION}-bin --strip-components=1
-    ln -s /kubedoop/phoenix-${HBASE_PROFILE_VERSION}-${PHOENIX_VERSION}-bin /kubedoop/phoenix
-    popd
-
-EOF
+#     # cleanup cache
+#     rm -rf /root/.m2
+# EOF
 
 
-## stage: hadoop-builder
-FROM zncdatadev/image/hadoop AS hadoop-builder
+# ## stage: hadoop-builder
+# FROM zncdatadev/image/hadoop AS hadoop
 
 
-## stage: hadoop-s3-builder
-FROM zncdatadev/image/java-devel AS hadoop-s3-builder
+# ## stage: hadoop-s3-builder
+# FROM zncdatadev/image/java-devel AS hadoop-s3-builder
 
-ARG HADOOP_VERSION
+# ARG HADOOP_VERSION
 
-COPY --from=hadoop-builder \
-    /kubedoop/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar \
-    /kubedoop/hadoop/share/hadoop/tools/lib/hadoop-aws-${HADOOP_VERSION}.jar \
-    /kubedoop/hadoop/share/hadoop/tools/lib/
+# COPY --from=hadoop \
+#     /kubedoop/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar \
+#     /kubedoop/hadoop/share/hadoop/tools/lib/hadoop-aws-${HADOOP_VERSION}.jar \
+#     /kubedoop/hadoop/share/hadoop/tools/lib/
 
 
 ## stage: final
@@ -243,37 +238,7 @@ ARG PRODUCT_VERSION
 ARG HBASE_PROFILE_VERSION
 
 RUN <<EOF
-    set -e
     microdnf update
-    microdnf install \
-        gzip \
-        python \
-        python-pip \
-        tar \
-        zip
-    microdnf clean all
-EOF
-
-WORKDIR /kubedoop
-
-COPY --from=java-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
-
-# setup hbase-operator-tools
-COPY --from=hbase-operator-tools-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
-
-# setup async-profiler
-COPY --from=async-profiler-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
-
-# setup phoenix
-COPY --from=phoenix-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
-
-# setup hadoop-s3
-COPY --from=hadoop-s3-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
-
-
-RUN <<EOF
-    microdnf update
-
     microdnf install \
         findutils \
         gzip \
@@ -284,10 +249,20 @@ RUN <<EOF
 
     microdnf clean all
     rm -rf /var/cache/yum
-
-    find /kubedoop/hadoop/share/ -name *.jar | grep 'aws' | xargs -I {} ln -s {} /kubedoop/hbase/lib/
-    ln -s /kubedoop/phoenix/phoenix-server-hbase-${HBASE_PROFILE_VERSION}.jar /kubedoop/hbase/lib/
 EOF
+
+WORKDIR /kubedoop
+
+COPY --from=hbase-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
+# # setup hbase-operator-tools
+# COPY --from=hbase-operator-tools-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
+# # setup phoenix
+# COPY --from=phoenix-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
+# # setup hadoop-s3
+# COPY --from=hadoop-s3-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
+
+# RUN find /kubedoop/hadoop/share/ -name *.jar | grep 'aws' | xargs -I {} ln -s {} /kubedoop/hbase/lib/ \
+#     && ln -s /kubedoop/phoenix/phoenix-server-hbase-${HBASE_PROFILE_VERSION}.jar /kubedoop/hbase/lib/
 
 ENV HBASE_HOME=/kubedoop/hbase
 
diff --git a/hive/Dockerfile b/hive/Dockerfile
--- a/hive/Dockerfile
+++ b/hive/Dockerfile
@@ -1,8 +1,9 @@
 # syntax=docker/dockerfile:1
 # check=error=true
 
-## stage: java-builder
-FROM zncdatadev/image/java-devel AS java-builder
+
+## stage: hive-builder
+FROM zncdatadev/image/java-devel AS hive-builder
 
 ARG PRODUCT_VERSION
 ARG JMX_EXPORTER_VERSION
@@ -27,7 +28,8 @@ EOF
 
 COPY kubedoop/ /build/
 
-RUN <<EOF
+RUN --mount=type=cache,target=/root/.m2 <<EOF
+    set -ex
     mkdir -p /build/hive-src
     pushd /build/hive-src
     curl -sSfL \
@@ -55,6 +57,9 @@ RUN <<EOF
 
     ln -s /kubedoop/apache-hive-metastore-${PRODUCT_VERSION}-bin /kubedoop/hive-metastore
     popd
+
+    # cleanup source
+    rm -rf /build/hive-src
 EOF
 
 COPY kubedoop/bin/start-metastore /kubedoop/hive-metastore/bin/
@@ -63,6 +68,7 @@ COPY kubedoop/bin/start-metastore /kubedoop/hive-metastore/bin/
 RUN /kubedoop/hive-metastore/bin/start-metastore --help
 
 
+## stage: hadoop
 FROM zncdatadev/image/hadoop AS hadoop
 
 
@@ -74,7 +80,7 @@ ARG HADOOP_VERSION
 
 WORKDIR /kubedoop
 
-COPY --from=java-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
+COPY --from=hive-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
 # When start the hive-metastore, it will try to load the hadoop configuration from the classpath.
 COPY --from=hadoop --chown=kubedoop:kubedoop /kubedoop/hadoop-${HADOOP_VERSION} /kubedoop/hadoop-${HADOOP_VERSION}
 
