refactor: build cache

diff --git a/spark-k8s/Dockerfile b/spark-k8s/Dockerfile
--- a/spark-k8s/Dockerfile
+++ b/spark-k8s/Dockerfile
@@ -1,4 +1,5 @@
 # syntax=docker/dockerfile:1
+# check=error=true
 
 
 FROM docker.io/library/gradle:8 AS gradle-builder
@@ -57,21 +58,15 @@ WORKDIR /build
 # setup jmx_exporter
 COPY kubedoop/jmx/config-${JMX_EXPORTER_VERSION} /kubedoop/jmx
 RUN <<EOF
-    set -e
-    # check JMX_EXPORTER_VERSION
-    if [ -n "${JMX_EXPORTER_VERSION}" ]; then
-        curl -sSfL \
-            https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${JMX_EXPORTER_VERSION}/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar \
-            -o /kubedoop/jmx/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar
+    curl -sSfL \
+    https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${JMX_EXPORTER_VERSION}/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar \
+    -o /kubedoop/jmx/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar
 
-        ln -s /kubedoop/jmx/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar /kubedoop/jmx/jmx_prometheus_javaagent.jar
-    else
-        echo "JMX_EXPORTER_VERSION is not set"
-    fi
+    ln -s /kubedoop/jmx/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar /kubedoop/jmx/jmx_prometheus_javaagent.jar
 EOF
 
 # build spark
-RUN <<EOF
+RUN --mount=type=cache,target=/root/.m2 <<EOF
     set -e
     mkdir -p /build/spark-src
     pushd /build/spark-src
@@ -92,26 +87,29 @@ RUN <<EOF
     ln -s /kubedoop/spark-${PRODUCT_VERSION} /kubedoop/spark
     ln -s /kubedoop/spark/jars/spark-examples_*.jar /kubedoop/spark/examples.jar
     popd
+
+    # smoke test
+    /kubedoop/spark/bin/spark-shell --version
+
+    # cleanup source
+    rm -rf /build/spark-src
 EOF
 
 COPY --from=gradle-builder /jars/ /kubedoop/spark/jars/
 
-# smoke test
-RUN /kubedoop/spark/bin/spark-shell --version
-
+# setup oauth2-proxy
 RUN <<EOF
-set -ex
-ARCH=$(uname -m)
-ARCH="${ARCH/x86_64/amd64}"
-ARCH="${ARCH/aarch64/arm64}"
+    set -ex
+    ARCH=$(uname -m)
+    ARCH="${ARCH/x86_64/amd64}"
+    ARCH="${ARCH/aarch64/arm64}"
 
-mkdir /kubedoop/oauth2-proxy
-cd /kubedoop/oauth2-proxy
+    mkdir /kubedoop/oauth2-proxy
+    cd /kubedoop/oauth2-proxy
 
-curl -sSfL \
-    https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-${ARCH}.tar.gz \
-    | tar xzf - --strip-components=1
-
+    curl -sSfL \
+        https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-${ARCH}.tar.gz \
+        | tar xzf - --strip-components=1
 EOF
 
 # smoke test
@@ -135,6 +133,8 @@ RUN <<EOF
         zip
 
     microdnf clean all
+    rm -rf /var/cache/yum
+
     ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python
     ln -s /usr/bin/pip-${PYTHON_VERSION} /usr/bin/pip
 EOF
@@ -142,16 +142,9 @@ EOF
 COPY --from=java-builder --chown=kubedoop:kubedoop /kubedoop/ /kubedoop/
 
 ENV SPARK_HOME=/kubedoop/spark
-
-RUN <<EOT
-    set -e
-    cat >> /etc/profile.d/spark.sh <<'EOF'
-export PATH=${SPARK_HOME}/bin:${PATH}
-export PYSPARK_PYTHON=/usr/bin/python
-export PYTHONPATH=${SPARK_HOME}/python:${PYTHONPATH}
-EOF
-
-EOT
+ENV PATH="${SPARK_HOME}/bin:${PATH}" \
+    PYSPARK_PYTHON=/usr/bin/python \
+    PYTHONPATH="${SPARK_HOME}/python:${PYTHONPATH}"
 
 WORKDIR /kubedoop/spark
 
